[package]
name = "cbor"
authors = ["Dane Stuckel <dane.stuckel@gmail.com>"]
edition = "2021"
readme = "README.md"

include = ["/src"]

[lib]
bench = false

[dependencies]

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports", "async_futures"] }
common-testing = "1.1.1"
