[package]
name = "cbor-cli"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.12", features = ["env", "derive"] }
colored = { version = "2.1.0" }
cbor = { path="../cbor" }
