name: Rust Cross-Compilation

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-unknown-linux-gnu # Linux x86_64
          - i686-unknown-linux-gnu # Linux x86
          - aarch64-unknown-linux-gnu # Linux ARM64
          - arm-unknown-linux-gnueabihf # Linux ARMv7
          # - x86_64-apple-darwin # macOS x86_64
          # - aarch64-apple-darwin # macOS ARM64 (Apple Silicon)
          # Add other targets as needed

    steps:
      - uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Install ARM cross-compilation tools for aarch64
        if: matrix.target == 'aarch64-unknown-linux-gnu'
        run: sudo apt-get install -y binutils-aarch64-linux-gnu

      - name: Install ARM cross-compilation tools for armv7
        if: matrix.target == 'arm-unknown-linux-gnueabihf'
        run: sudo apt-get install -y binutils-arm-linux-gnueabihf

      - name: Install cross
        run: cargo install cross

      - name: Build with cross
        run: cross build --target ${{ matrix.target }} --release

      - name: Copy License
        run: cp LICENSE target/${{ matrix.target }}/release/

      - name: Compress Binary and License
        run: tar -czvf cbor-${{ matrix.target }}.tar.gz -C target/${{ matrix.target }}/release cbor LICENSE

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cbor-${{ matrix.target }}
          path: cbor-${{ matrix.target }}.tar.gz

      - name: Install cargo-deb
        run: cargo install cargo-deb

      - name: Create Debian Package
        run: cargo deb --target ${{ matrix.target }} --no-build

      - name: Upload Debian Package
        uses: actions/upload-artifact@v4
        with:
          name: cbor-${{ matrix.target }}.deb
          path: target/${{ matrix.target }}/debian/cbor*.deb
